name: Flags
author: MattBcool
version: 1
description: A plugin to create animated flags in Minecraft.
main: com.mattbcool.main.Main
api-version: 1.13
commands:
    flag:
        description: Modify aspects of flags
        aliases: [flags]